// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// em_impute_rcpp
arma::mat em_impute_rcpp(arma::mat data, int max_iter, double tol);
RcppExport SEXP _SA24204177_em_impute_rcpp(SEXP dataSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(em_impute_rcpp(data, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// Gibbs_rcpp
NumericMatrix Gibbs_rcpp(int n, int a, int b, int num_samples, int out);
RcppExport SEXP _SA24204177_Gibbs_rcpp(SEXP nSEXP, SEXP aSEXP, SEXP bSEXP, SEXP num_samplesSEXP, SEXP outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type out(outSEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_rcpp(n, a, b, num_samples, out));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204177_em_impute_rcpp", (DL_FUNC) &_SA24204177_em_impute_rcpp, 3},
    {"_SA24204177_Gibbs_rcpp", (DL_FUNC) &_SA24204177_Gibbs_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204177(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
